### ISSUE TITLE
User can upload a file

### ISSUE THREAD

**Issue by StevenNagata** [StevenNagata/Job-Lander#24]
# 🤑 Motivation
Users will want to  upload files they sent or received from a job prospect
.
# 🗺 Plan
Define functionality that lets a user upload a file to a job prospect 

# Research Task List
- [x] Set up an s3 bucket on aws
- [x] Get a successful Post request to a basic express server using multer (test with HTTPie)
- [x] Add a web page with a form to post to previous express server
- [x] Write a Js files that uploads to s3 (test with node command)
- [x] Add multer-s3 to express server to upload directly to s3 from HTTPie or browser
- [x] Edit express server to update a db.json file when a request is made
- [x] Research issues that can fix db.json conflicts when more than one router.

# Task List
- [x] Add a form component to upload files to into the 
- [x] Add an add files button to each job prospect details page.
- [x] Add the researched express functionality to the index.js file
- [x] Add bucket name, user key and secret key to the .env file 
- [x] Change the form input file component to make form data an pass it as a fetch to the db.json.
- [x] Add a react createRef to fire the input file pop up

# 🖼 Wire Frame
![final-project](https://occs.mybalsamiq.com/mockups/6628440.png?key=5e42409fa1b2e898543d50ac0d98e174a8ad86a7)
